#!/bin/zsh

#check if there is one argument, which is the file name
if (( $#==1 )) ; then
    # check if there is another file with that name
    NOMEFILE=$(ls | grep $1)
    if [ "$1" = "${NOMEFILE}" ] ; then
        echo "A file with this name already exists"
        exit 1
    else
        # create a new file and give to it execution permissions
        touch $1
        chmod u+x $1
        echo "File created successfully"
        ls -lh | grep $1
        exit 0
    fi
else
    echo "usage: mkscript [filename]"
    exit 1
fi
